
"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "ar" | "fr"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.products": "Products",
    "nav.collections": "Collections",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.cart": "Cart",
    "nav.wishlist": "Wishlist",
    "nav.admin": "Admin",
    "nav.orders": "Orders",
    "nav.faq": "FAQ",
    "nav.shipping": "Shipping",

    // Common
    "common.search": "Search",
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.add": "Add",
    "common.create": "Create",
    "common.update": "Update",
    "common.price": "Price",
    "common.quantity": "Quantity",
    "common.total": "Total",
    "common.submit": "Submit",
    "common.close": "Close",
    "common.view": "View",
    "common.viewAll": "View All",
    "common.learnMore": "Learn More",
    "common.shopNow": "Shop Now",
    "common.viewDetails": "View Details",
    "common.subscribe": "Subscribe",
    "common.send": "Send",
    "common.name": "Name",
    "common.email": "Email",
    "common.message": "Message",
    "common.subject": "Subject",
    "common.category": "Category",
    "common.status": "Status",
    "common.date": "Date",
    "common.actions": "Actions",
    "common.description": "Description",
    "common.features": "Features",
    "common.specifications": "Specifications",
    "common.reviews": "Reviews",
    "common.rating": "Rating",

    // Products
    "product.addToCart": "Add to Cart",
    "product.addToWishlist": "Add to Wishlist",
    "product.removeFromWishlist": "Remove from Wishlist",
    "product.outOfStock": "Out of Stock",
    "product.inStock": "In Stock",
    "product.featured": "Featured",
    "product.sale": "Sale",
    "product.new": "New",
    "product.bestSeller": "Best Seller",
    "product.eco": "Eco",
    "product.premium": "Premium",
    "product.originalPrice": "Original Price",
    "product.currentPrice": "Current Price",
    "product.selectVariant": "Select Variant",
    "product.color": "Color",
    "product.size": "Size",
    "product.feature": "Feature",

    // Cart & Checkout
    "cart.title": "Shopping Cart",
    "cart.empty": "Your cart is empty",
    "cart.continueShopping": "Continue Shopping",
    "cart.proceedToCheckout": "Proceed to Checkout",
    "cart.removeItem": "Remove Item",
    "cart.updateQuantity": "Update Quantity",
    "cart.subtotal": "Subtotal",
    "cart.shipping": "Shipping",
    "cart.tax": "Tax",
    "cart.total": "Total",
    "checkout.title": "Checkout",
    "checkout.billingAddress": "Billing Address",
    "checkout.shippingAddress": "Shipping Address",
    "checkout.paymentMethod": "Payment Method",
    "checkout.placeOrder": "Place Order",

    // Wishlist
    "wishlist.title": "My Wishlist",
    "wishlist.empty": "Your wishlist is empty",
    "wishlist.addedToCart": "Added to cart",
    "wishlist.removedFromWishlist": "Removed from wishlist",

    // Search
    "search.title": "Search Results",
    "search.noResults": "No products found",
    "search.resultsFor": "Results for",
    "search.filters": "Filters",
    "search.sortBy": "Sort by",
    "search.clearFilters": "Clear all filters",

    // Admin
    "admin.dashboard": "Dashboard",
    "admin.products": "Products",
    "admin.orders": "Orders",
    "admin.landingPages": "Landing Pages",
    "admin.templates": "Templates",
    "admin.settings": "Settings",
    "admin.overview": "Overview",
    "admin.analytics": "Analytics",
    "admin.customers": "Customers",
    "admin.addProduct": "Add Product",
    "admin.editProduct": "Edit Product",
    "admin.deleteProduct": "Delete Product",
    "admin.productName": "Product Name",
    "admin.productPages": "Product Pages",
    "admin.productDescription": "Product Description",
    "admin.productPrice": "Product Price",
    "admin.productCategory": "Product Category",
    "admin.productStock": "Product Stock",
    "admin.productImages": "Product Images",
    "admin.productVariants": "Product Variants",
    "admin.addVariant": "Add Variant",
    "admin.variantType": "Variant Type",
    "admin.variantValue": "Variant Value",
    "admin.variantDescription": "Variant Description",
    "admin.variantImages": "Variant Images",
    "admin.variantStock": "Variant Stock",

    // Admin Dashboard
    "admin.totalRevenue": "Total Revenue",
    "admin.totalOrders": "Orders",
    "admin.totalProducts": "Products",
    "admin.activeCustomers": "Active Customers",
    "admin.recentSales": "Recent Sales",
    "admin.salesThisMonth": "You made 265 sales this month.",

    // Admin Products
    "admin.productList": "Product List",
    "admin.productListDesc": "A list of all products in your store with variants",
    "admin.searchProducts": "Search products...",
    "admin.image": "Image",
    "admin.variants": "Variants",
    "admin.moreVariants": "more",
    "admin.basicInfo": "Basic Info",
    "admin.images": "Images",
    "admin.preview": "Preview",
    "admin.addImage": "Add Image",
    "admin.imageUrl": "Image URL",
    "admin.altText": "Alt Text",
    "admin.primaryImage": "Primary Image",
    "admin.noImagesAdded": "No images added yet",
    "admin.clickAddImage": 'Click "Add Image" to get started',
    "admin.variantName": "Variant Name",
    "admin.type": "Type",
    "admin.value": "Value",
    "admin.stockQuantity": "Stock Quantity",
    "admin.noVariantsAdded": "No variants added yet",
    "admin.clickAddVariant": 'Click "Add Variant" to create color, size, or feature options',
    "admin.productPreview": "Product Preview",
    "admin.availableOptions": "Available Options:",
    "admin.units": "units",

    // Admin Orders
    "admin.manageOrders": "Manage customer orders and track fulfillment",
    "admin.searchOrders": "Search orders...",
    "admin.newOrder": "New Order",
    "admin.filterByStatus": "Filter by status",
    "admin.allStatus": "All Status",
    "admin.pending": "Pending",
    "admin.processing": "Processing",
    "admin.shipped": "Shipped",
    "admin.delivered": "Delivered",
    "admin.cancelled": "Cancelled",
    "admin.orderList": "Order List",
    "admin.recentOrders": "Recent orders from your customers",
    "admin.orderId": "Order ID",
    "admin.customer": "Customer",
    "admin.orderDetails": "Order Details",
    "admin.completeOrderInfo": "Complete order information and customer details",
    "admin.customerInfo": "Customer Information",
    "admin.orderDate": "Order Date",
    "admin.shippingAddress": "Shipping Address",

    // Admin Templates
    "admin.landingPageTemplates": "Landing Page Templates",
    "admin.createManageTemplates": "Create and manage reusable templates for landing pages",
    "admin.quickTemplate": "Quick Template",
    "admin.buildTemplate": "Build Template",
    "admin.createQuickTemplate": "Create Quick Template",
    "admin.basicTemplateCustomize": "Create a basic template that you can customize later",
    "admin.templateName": "Template Name",
    "admin.createTemplate": "Create Template",
    "admin.default": "Default",
    "admin.sections": "sections",
    "admin.created": "Created",

    // Admin Settings
    "admin.storeConfiguration": "Manage your store configuration and preferences",
    "admin.store": "Store",
    "admin.seo": "SEO",
    "admin.email": "Email",
    "admin.payment": "Payment",
    "admin.theme": "Theme",
    "admin.security": "Security",
    "admin.storeInformation": "Store Information",
    "admin.basicStoreInfo": "Basic information about your store",
    "admin.storeName": "Store Name",
    "admin.storeEmail": "Store Email",
    "admin.storeDescription": "Store Description",
    "admin.phoneNumber": "Phone Number",
    "admin.address": "Address",
    "admin.saveStoreSettings": "Save Store Settings",
    "admin.seoConfiguration": "SEO Configuration",
    "admin.optimizeStore": "Optimize your store for search engines",
    "admin.siteTitle": "Site Title",
    "admin.metaDescription": "Meta Description",
    "admin.keywords": "Keywords",
    "admin.analyticsTracking": "Analytics & Tracking",
    "admin.googleAnalyticsId": "Google Analytics ID",
    "admin.facebookPixelId": "Facebook Pixel ID",
    "admin.enableTracking": "Enable tracking and analytics",
    "admin.saveSeoSettings": "Save SEO Settings",
    "admin.emailConfiguration": "Email Configuration",
    "admin.configureEmailNotifications": "Configure email notifications and SMTP settings",
    "admin.notificationSettings": "Notification Settings",
    "admin.enableEmailNotifications": "Enable email notifications",
    "admin.sendOrderConfirmations": "Send order confirmations",
    "admin.sendMarketingEmails": "Send marketing emails",
    "admin.smtpConfiguration": "SMTP Configuration",
    "admin.smtpHost": "SMTP Host",
    "admin.smtpPort": "SMTP Port",
    "admin.smtpUsername": "SMTP Username",
    "admin.smtpPassword": "SMTP Password",
    "admin.saveEmailSettings": "Save Email Settings",
    "admin.paymentShipping": "Payment & Shipping",
    "admin.configurePaymentShipping": "Configure payment processing and shipping options",
    "admin.currency": "Currency",
    "admin.taxRate": "Tax Rate (%)",
    "admin.standardShippingRate": "Standard Shipping Rate",
    "admin.freeShippingThreshold": "Free Shipping Threshold",
    "admin.paymentMethods": "Payment Methods",
    "admin.active": "Active",
    "admin.inactive": "Inactive",
    "admin.creditCards": "Credit Cards",
    "admin.paypal": "PayPal",
    "admin.applePay": "Apple Pay",
    "admin.googlePay": "Google Pay",
    "admin.savePaymentSettings": "Save Payment Settings",
    "admin.themeCustomization": "Theme Customization",
    "admin.customizeStoreLook": "Customize the look and feel of your store",
    "admin.primaryColor": "Primary Color",
    "admin.secondaryColor": "Secondary Color",
    "admin.accentColor": "Accent Color",
    "admin.enableDarkMode": "Enable dark mode",
    "admin.logoBranding": "Logo & Branding",
    "admin.storeLogo": "Store Logo",
    "admin.uploadStoreLogo": "Upload your store logo",
    "admin.chooseFile": "Choose File",
    "admin.favicon": "Favicon",
    "admin.uploadFavicon": "Upload favicon (32x32px)",
    "admin.saveThemeSettings": "Save Theme Settings",
    "admin.securitySettings": "Security Settings",
    "admin.configureSecurityAuth": "Configure security and authentication options",
    "admin.enableTwoFactor": "Enable two-factor authentication",
    "admin.enforceStrongPasswords": "Enforce strong password requirements",
    "admin.sessionTimeout": "Session Timeout (minutes)",
    "admin.securityStatus": "Security Status",
    "admin.sslCertificate": "SSL Certificate",
    "admin.httpsEncryption": "HTTPS encryption",
    "admin.firewallProtection": "Firewall Protection",
    "admin.ddosProtection": "DDoS protection",
    "admin.saveSecuritySettings": "Save Security Settings",

    // Admin Navigation
    "admin.viewStore": "View Store",
    "admin.adminPanel": "Admin Panel",
    "admin.ecommerceAdmin": "E-commerce Admin",
    "admin.storePerformance": "Here's an overview of your store performance.",
    "admin.fromLastMonth": "from last month",
    "admin.sinceLastHour": "since last hour",

    // Home Page
    "home.hero.title": "Discover Amazing Products",
    "home.hero.subtitle":
      "Shop the latest trends and find everything you need in one place. Quality products, great prices, fast delivery.",
    "home.features.freeShipping": "Free Shipping",
    "home.features.freeShippingDesc": "Free shipping on orders over $50",
    "home.features.securePayment": "Secure Payment",
    "home.features.securePaymentDesc": "Your payment information is safe",
    "home.features.support": "24/7 Support",
    "home.features.supportDesc": "Get help whenever you need it",
    "home.featuredProducts.title": "Featured Products",
    "home.featuredProducts.subtitle": "Discover our most popular items, carefully selected for quality and value",
    "home.collections.title": "Shop by Collection",
    "home.collections.subtitle": "Explore our curated collections designed for every lifestyle",
    "home.newsletter.title": "Stay Updated",
    "home.newsletter.subtitle":
      "Subscribe to our newsletter and be the first to know about new products and exclusive offers",
    "home.newsletter.placeholder": "Enter your email",

    // About Page
    "about.title": "About Us",
    "about.subtitle": "Learn more about our company and mission",
    "about.story.title": "Our Story",
    "about.mission.title": "Our Mission",
    "about.values.title": "Our Values",
    "about.team.title": "Meet Our Team",

    // Contact Page
    "contact.title": "Get in Touch",
    "contact.subtitle":
      "Have a question, need support, or want to share feedback? We're here to help and would love to hear from you.",
    "contact.info.title": "Contact Information",
    "contact.info.email": "Email Us",
    "contact.info.phone": "Call Us",
    "contact.info.address": "Visit Us",
    "contact.info.hours": "Business Hours",
    "contact.form.title": "Send us a Message",
    "contact.form.subtitle": "Fill out the form below and we'll get back to you as soon as possible.",
    "contact.form.fullName": "Full Name",
    "contact.form.emailAddress": "Email Address",
    "contact.form.messageText": "Message",
    "contact.form.sendMessage": "Send Message",
    "contact.quickHelp.title": "Quick Help",
    "contact.quickHelp.trackOrder": "Track Your Order",
    "contact.quickHelp.trackOrderDesc": "Check order status and shipping",
    "contact.quickHelp.faq": "FAQ",
    "contact.quickHelp.faqDesc": "Find answers to common questions",
    "contact.quickHelp.liveChat": "Live Chat",
    "contact.quickHelp.liveChatDesc": "Chat with our support team",

    // FAQ Page
    "faq.title": "Frequently Asked Questions",
    "faq.subtitle": "Find answers to common questions about our products and services",
    "faq.searchPlaceholder": "Search FAQ...",

    // Footer
    "footer.company": "E-Store",
    "footer.companyDesc": "Your trusted online shopping destination for quality products at great prices.",
    "footer.quickLinks": "Quick Links",
    "footer.customerService": "Customer Service",
    "footer.connect": "Connect",
    "footer.connectDesc": "Follow us on social media for updates and exclusive offers.",
    "footer.copyright": "© 2024 E-Store. All rights reserved.",

    // Collections
    "collections.electronics": "Electronics",
    "collections.electronicsDesc": "Latest tech gadgets and accessories",
    "collections.lifestyle": "Lifestyle",
    "collections.lifestyleDesc": "Products for modern living",
    "collections.fitness": "Fitness",
    "collections.fitnessDesc": "Health and wellness essentials",
    "collections.products": "products",

    // Messages & Notifications
    "message.addedToCart": "Added to cart successfully!",
    "message.addedToWishlist": "Added to wishlist!",
    "message.removedFromWishlist": "Removed from wishlist",
    "message.messageSent": "Message sent successfully!",
    "message.subscribed": "Successfully subscribed to newsletter!",
    "message.error": "Something went wrong. Please try again.",
    "message.orderPlaced": "Order placed successfully!",
    "message.productSaved": "Product saved successfully!",
    "message.productDeleted": "Product deleted successfully!",

    // Form Validation
    "validation.required": "This field is required",
    "validation.email": "Please enter a valid email address",
    "validation.minLength": "Minimum length is {min} characters",
    "validation.maxLength": "Maximum length is {max} characters",
    "validation.numeric": "Please enter a valid number",
    "validation.positive": "Please enter a positive number",
  },
  ar: {
    // Navigation
    "nav.home": "الرئيسية",
    "nav.products": "المنتجات",
    "nav.collections": "المجموعات",
    "nav.about": "حولنا",
    "nav.contact": "اتصل بنا",
    "nav.cart": "السلة",
    "nav.wishlist": "المفضلة",
    "nav.admin": "الإدارة",
    "nav.orders": "الطلبات",
    "nav.faq": "الأسئلة الشائعة",
    "nav.shipping": "الشحن",

    // Common
    "common.search": "بحث",
    "common.loading": "جاري التحميل...",
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.add": "إضافة",
    "common.create": "إنشاء",
    "common.update": "تحديث",
    "common.price": "السعر",
    "common.quantity": "الكمية",
    "common.total": "المجموع",
    "common.submit": "إرسال",
    "common.close": "إغلاق",
    "common.view": "عرض",
    "common.viewAll": "عرض الكل",
    "common.learnMore": "اعرف المزيد",
    "common.shopNow": "تسوق الآن",
    "common.viewDetails": "عرض التفاصيل",
    "common.subscribe": "اشتراك",
    "common.send": "إرسال",
    "common.name": "الاسم",
    "common.email": "البريد الإلكتروني",
    "common.message": "الرسالة",
    "common.subject": "الموضوع",
    "common.category": "الفئة",
    "common.status": "الحالة",
    "common.date": "التاريخ",
    "common.actions": "الإجراءات",
    "common.description": "الوصف",
    "common.features": "المميزات",
    "common.specifications": "المواصفات",
    "common.reviews": "التقييمات",
    "common.rating": "التقييم",

    // Products
    "product.addToCart": "أضف للسلة",
    "product.addToWishlist": "أضف للمفضلة",
    "product.removeFromWishlist": "إزالة من المفضلة",
    "product.outOfStock": "غير متوفر",
    "product.inStock": "متوفر",
    "product.featured": "مميز",
    "product.sale": "تخفيض",
    "product.new": "جديد",
    "product.bestSeller": "الأكثر مبيعاً",
    "product.eco": "صديق للبيئة",
    "product.premium": "مميز",
    "product.originalPrice": "السعر الأصلي",
    "product.currentPrice": "السعر الحالي",
    "product.selectVariant": "اختر النوع",
    "product.color": "اللون",
    "product.size": "الحجم",
    "product.feature": "الميزة",

    // Cart & Checkout
    "cart.title": "سلة التسوق",
    "cart.empty": "سلة التسوق فارغة",
    "cart.continueShopping": "متابعة التسوق",
    "cart.proceedToCheckout": "إتمام الطلب",
    "cart.removeItem": "إزالة العنصر",
    "cart.updateQuantity": "تحديث الكمية",
    "cart.subtotal": "المجموع الفرعي",
    "cart.shipping": "الشحن",
    "cart.tax": "الضريبة",
    "cart.total": "المجموع الكلي",
    "checkout.title": "إتمام الطلب",
    "checkout.billingAddress": "عنوان الفواتير",
    "checkout.shippingAddress": "عنوان الشحن",
    "checkout.paymentMethod": "طريقة الدفع",
    "checkout.placeOrder": "تأكيد الطلب",

    // Wishlist
    "wishlist.title": "قائمة المفضلة",
    "wishlist.empty": "قائمة المفضلة فارغة",
    "wishlist.addedToCart": "تم إضافته للسلة",
    "wishlist.removedFromWishlist": "تم إزالته من المفضلة",

    // Search
    "search.title": "نتائج البحث",
    "search.noResults": "لم يتم العثور على منتجات",
    "search.resultsFor": "نتائج البحث عن",
    "search.filters": "المرشحات",
    "search.sortBy": "ترتيب حسب",
    "search.clearFilters": "مسح جميع المرشحات",

    // Admin
    "admin.dashboard": "لوحة التحكم",
    "admin.products": "المنتجات",
    "admin.orders": "الطلبات",
    "admin.landingPages": "صفحات الهبوط",
    "admin.templates": "القوالب",
    "admin.settings": "الإعدادات",
    "admin.overview": "نظرة عامة",
    "admin.analytics": "التحليلات",
    "admin.productPages": "صفحات المنتجات",
    "admin.customers": "العملاء",
    "admin.addProduct": "إضافة منتج",
    "admin.editProduct": "تعديل منتج",
    "admin.deleteProduct": "حذف منتج",
    "admin.productName": "اسم المنتج",
    "admin.productDescription": "وصف المنتج",
    "admin.productPrice": "سعر المنتج",
    "admin.productCategory": "فئة المنتج",
    "admin.productStock": "مخزون المنتج",
    "admin.productImages": "صور المنتج",
    "admin.productVariants": "أنواع المنتج",
    "admin.addVariant": "إضافة نوع",
    "admin.variantType": "نوع التنويع",
    "admin.variantValue": "قيمة التنويع",
    "admin.variantDescription": "وصف التنويع",
    "admin.variantImages": "صور التنويع",
    "admin.variantStock": "مخزون التنويع",

    // Admin Dashboard
    "admin.totalRevenue": "إجمالي الإيرادات",
    "admin.totalOrders": "الطلبات",
    "admin.totalProducts": "المنتجات",
    "admin.activeCustomers": "العملاء النشطون",
    "admin.recentSales": "المبيعات الأخيرة",
    "admin.salesThisMonth": "لقد حققت 265 عملية بيع هذا الشهر.",

    // Admin Products
    "admin.productList": "قائمة المنتجات",
    "admin.productListDesc": "قائمة بجميع المنتجات في متجرك مع المتغيرات",
    "admin.searchProducts": "البحث في المنتجات...",
    "admin.image": "الصورة",
    "admin.variants": "المتغيرات",
    "admin.moreVariants": "المزيد",
    "admin.basicInfo": "المعلومات الأساسية",
    "admin.images": "الصور",
    "admin.preview": "معاينة",
    "admin.addImage": "إضافة صورة",
    "admin.imageUrl": "رابط الصورة",
    "admin.altText": "النص البديل",
    "admin.primaryImage": "الصورة الأساسية",
    "admin.noImagesAdded": "لم يتم إضافة صور بعد",
    "admin.clickAddImage": 'انقر على "إضافة صورة" للبدء',
    "admin.variantName": "اسم المتغير",
    "admin.type": "النوع",
    "admin.value": "القيمة",
    "admin.stockQuantity": "كمية المخزون",
    "admin.noVariantsAdded": "لم يتم إضافة متغيرات بعد",
    "admin.clickAddVariant": 'انقر على "إضافة متغير" لإنشاء خيارات اللون أو الحجم أو الميزة',
    "admin.productPreview": "معاينة المنتج",
    "admin.availableOptions": "الخيارات المتاحة:",
    "admin.units": "وحدة",

    // Admin Orders
    "admin.manageOrders": "إدارة طلبات العملاء وتتبع التنفيذ",
    "admin.searchOrders": "البحث في الطلبات...",
    "admin.newOrder": "إنشاء طلبية جديدة",
    "admin.filterByStatus": "تصفية حسب الحالة",
    "admin.allStatus": "جميع الحالات",
    "admin.pending": "قيد الانتظار",
    "admin.processing": "جاري المعالجة",
    "admin.shipped": "تم الشحن",
    "admin.delivered": "تم التسليم",
    "admin.cancelled": "تم الإلغاء",
    "admin.orderList": "قائمة الطلبات",
    "admin.recentOrders": "أحدث الطلبات من عملائك",
    "admin.orderId": "رقم التعريف الخاص بالطلب",
    "admin.customer": "العميل",
    "admin.orderDetails": "تفاصيل الطلب",
    "admin.completeOrderInfo": "معلومات الطلب الكاملة وتفاصيل العميل",
    "admin.customerInfo": "معلومات العميل",
    "admin.orderDate": "تاريخ الطلب",
    "admin.shippingAddress": "عنوان الشحن",

    // Admin Templates
    "admin.landingPageTemplates": "قوالب الصفحة المقصودة",
    "admin.createManageTemplates": "إنشاء وإدارة قوالب قابلة لإعادة الاستخدام للصفحات المقصودة",
    "admin.quickTemplate": "قالب سريع",
    "admin.buildTemplate": "بناء قالب",
    "admin.createQuickTemplate": "إنشاء قالب سريع",
    "admin.basicTemplateCustomize": "إنشاء قالب أساسي يمكنك تخصيصه لاحقًا",
    "admin.templateName": "اسم القالب",
    "admin.createTemplate": "إنشاء قالب",
    "admin.default": "افتراضي",
    "admin.sections": "الأقسام",
    "admin.created": "تم الإنشاء",

    // Admin Settings
    "admin.storeConfiguration": "إدارة تكوين المتجر وتفضيلاته",
    "admin.store": "المتجر",
    "admin.seo": "تحسين محركات البحث",
    "admin.email": "البريد الإلكتروني",
    "admin.payment": "الدفع",
    "admin.theme": "السمة",
    "admin.security": "الأمان",
    "admin.storeInformation": "معلومات المتجر",
    "admin.basicStoreInfo": "معلومات أساسية حول متجرك",
    "admin.storeName": "اسم المتجر",
    "admin.storeEmail": "البريد الإلكتروني للمتجر",
    "admin.storeDescription": "وصف المتجر",
    "admin.phoneNumber": "رقم الهاتف",
    "admin.address": "العنوان",
    "admin.saveStoreSettings": "حفظ إعدادات المتجر",
    "admin.seoConfiguration": "تكوين تحسين محركات البحث",
    "admin.optimizeStore": "تحسين متجرك لمحركات البحث",
    "admin.siteTitle": "عنوان الموقع",
    "admin.metaDescription": "الوصف التعريفي",
    "admin.keywords": "الكلمات المفتاحية",
    "admin.analyticsTracking": "التحليلات والتتبع",
    "admin.googleAnalyticsId": "معرف تحليلات جوجل",
    "admin.facebookPixelId": "معرف فيسبوك بكسل",
    "admin.enableTracking": "تمكين التتبع والتحليلات",
    "admin.saveSeoSettings": "حفظ إعدادات تحسين محركات البحث",
    "admin.emailConfiguration": "تكوين البريد الإلكتروني",
    "admin.configureEmailNotifications": "تكوين إشعارات البريد الإلكتروني وإعدادات SMTP",
    "admin.notificationSettings": "إعدادات الإشعارات",
    "admin.enableEmailNotifications": "تمكين إشعارات البريد الإلكتروني",
    "admin.sendOrderConfirmations": "إرسال تأكيدات الطلب",
    "admin.sendMarketingEmails": "إرسال رسائل بريد إلكتروني تسويقية",
    "admin.smtpConfiguration": "تكوين SMTP",
    "admin.smtpHost": "مضيف SMTP",
    "admin.smtpPort": "منفذ SMTP",
    "admin.smtpUsername": "اسم مستخدم SMTP",
    "admin.smtpPassword": "كلمة مرور SMTP",
    "admin.saveEmailSettings": "حفظ إعدادات البريد الإلكتروني",
    "admin.paymentShipping": "الدفع والشحن",
    "admin.configurePaymentShipping": "تكوين معالجة الدفع وخيارات الشحن",
    "admin.currency": "العملة",
    "admin.taxRate": "معدل الضريبة (%)",
    "admin.standardShippingRate": "سعر الشحن القياسي",
    "admin.freeShippingThreshold": "حد الشحن المجاني",
    "admin.paymentMethods": "طرق الدفع",
    "admin.active": "نشط",
    "admin.inactive": "غير نشط",
    "admin.creditCards": "بطاقات الائتمان",
    "admin.paypal": "باي بال",
    "admin.applePay": "أبل باي",
    "admin.googlePay": "جوجل باي",
    "admin.savePaymentSettings": "حفظ إعدادات الدفع",
    "admin.themeCustomization": "تخصيص المظهر",
    "admin.customizeStoreLook": "تخصيص شكل ومظهر متجرك",
    "admin.primaryColor": "اللون الأساسي",
    "admin.secondaryColor": "اللون الثانوي",
    "admin.accentColor": "لون التمييز",
    "admin.enableDarkMode": "تمكين الوضع الداكن",
    "admin.logoBranding": "الشعار والعلامة التجارية",
    "admin.storeLogo": "شعار المتجر",
    "admin.uploadStoreLogo": "تحميل شعار متجرك",
    "admin.chooseFile": "اختر ملفا",
    "admin.favicon": "أيقونة الموقع",
    "admin.uploadFavicon": "تحميل أيقونة الموقع (32 × 32 بكسل)",
    "admin.saveThemeSettings": "حفظ إعدادات المظهر",
    "admin.securitySettings": "إعدادات الأمان",
    "admin.configureSecurityAuth": "تكوين خيارات الأمان والمصادقة",
    "admin.enableTwoFactor": "تمكين المصادقة الثنائية",
    "admin.enforceStrongPasswords": "فرض متطلبات كلمة مرور قوية",
    "admin.sessionTimeout": "مهلة الجلسة (بالدقائق)",
    "admin.securityStatus": "حالة الأمان",
    "admin.sslCertificate": "شهادة SSL",
    "admin.httpsEncryption": "تشفير HTTPS",
    "admin.firewallProtection": "حماية جدار الحماية",
    "admin.ddosProtection": "حماية DDoS",
    "admin.saveSecuritySettings": "حفظ إعدادات الأمان",

    // Admin Navigation
    "admin.viewStore": "عرض المتجر",
    "admin.adminPanel": "لوحة الإدارة",
    "admin.ecommerceAdmin": "إدارة التجارة الإلكترونية",
    "admin.storePerformance": "إليك نظرة عامة على أداء متجرك.",
    "admin.fromLastMonth": "من الشهر الماضي",
    "admin.sinceLastHour": "منذ الساعة الماضية",

    // Home Page
    "home.hero.title": "اكتشف منتجات مذهلة",
    "home.hero.subtitle":
      "تسوق أحدث الصيحات واعثر على كل ما تحتاجه في مكان واحد. منتجات عالية الجودة، أسعار رائعة، توصيل سريع.",
    // Home Page
    "home.features.freeShipping": "شحن مجاني",
    "home.features.freeShippingDesc": "شحن مجاني للطلبات أكثر من 50 دولار",
    "home.features.securePayment": "دفع آمن",
    "home.features.securePaymentDesc": "معلومات الدفع الخاصة بك آمنة",
    "home.features.support": "دعم 24/7",
    "home.features.supportDesc": "احصل على المساعدة متى احتجتها",
    "home.featuredProducts.title": "المنتجات المميزة",
    "home.featuredProducts.subtitle": "اكتشف أكثر منتجاتنا شعبية، مختارة بعناية للجودة والقيمة",
    "home.collections.title": "تسوق حسب المجموعة",
    "home.collections.subtitle": "استكشف مجموعاتنا المنسقة المصممة لكل نمط حياة",
    "home.newsletter.title": "ابق على اطلاع",
    "home.newsletter.subtitle": "اشترك في نشرتنا الإخبارية وكن أول من يعرف عن المنتجات الجديدة والعروض الحصرية",
    "home.newsletter.placeholder": "أدخل بريدك الإلكتروني",

    // About Page
    "about.title": "حولنا",
    "about.subtitle": "تعرف أكثر على شركتنا ومهمتنا",
    "about.story.title": "قصتنا",
    "about.mission.title": "مهمتنا",
    "about.values.title": "قيمنا",
    "about.team.title": "تعرف على فريقنا",

    // Contact Page
    "contact.title": "تواصل معنا",
    "contact.subtitle": "هل لديك سؤال، تحتاج دعم، أو تريد مشاركة ملاحظات؟ نحن هنا للمساعدة ونحب أن نسمع منك.",
    "contact.info.title": "معلومات الاتصال",
    "contact.info.email": "راسلنا",
    "contact.info.phone": "اتصل بنا",
    "contact.info.address": "زرنا",
    "contact.info.hours": "ساعات العمل",
    "contact.form.title": "أرسل لنا رسالة",
    "contact.form.subtitle": "املأ النموذج أدناه وسنعود إليك في أقرب وقت ممكن.",
    "contact.form.fullName": "الاسم الكامل",
    "contact.form.emailAddress": "عنوان البريد الإلكتروني",
    "contact.form.messageText": "الرسالة",
    "contact.form.sendMessage": "إرسال الرسالة",
    "contact.quickHelp.title": "مساعدة سريعة",
    "contact.quickHelp.trackOrder": "تتبع طلبك",
    "contact.quickHelp.trackOrderDesc": "تحقق من حالة الطلب والشحن",
    "contact.quickHelp.faq": "الأسئلة الشائعة",
    "contact.quickHelp.faqDesc": "اعثر على إجابات للأسئلة الشائعة",
    "contact.quickHelp.liveChat": "دردشة مباشرة",
    "contact.quickHelp.liveChatDesc": "تحدث مع فريق الدعم",

    // FAQ Page
    "faq.title": "الأسئلة الشائعة",
    "faq.subtitle": "اعثر على إجابات للأسئلة الشائعة حول منتجاتنا وخدماتنا",
    "faq.searchPlaceholder": "البحث في الأسئلة الشائعة...",

    // Footer
    "footer.company": "المتجر الإلكتروني",
    "footer.companyDesc": "وجهتك الموثوقة للتسوق الإلكتروني للمنتجات عالية الجودة بأسعار رائعة.",
    "footer.quickLinks": "روابط سريعة",
    "footer.customerService": "خدمة العملاء",
    "footer.connect": "تواصل",
    "footer.connectDesc": "تابعنا على وسائل التواصل الاجتماعي للحصول على التحديثات والعروض الحصرية.",
    "footer.copyright": "© 2024 المتجر الإلكتروني. جميع الحقوق محفوظة.",

    // Collections
    "collections.electronics": "الإلكترونيات",
    "collections.electronicsDesc": "أحدث الأجهزة التقنية والإكسسوارات",
    "collections.lifestyle": "نمط الحياة",
    "collections.lifestyleDesc": "منتجات للحياة العصرية",
    "collections.fitness": "اللياقة البدنية",
    "collections.fitnessDesc": "أساسيات الصحة والعافية",
    "collections.products": "منتجات",

    // Messages & Notifications
    "message.addedToCart": "تم إضافته للسلة بنجاح!",
    "message.addedToWishlist": "تم إضافته للمفضلة!",
    "message.removedFromWishlist": "تم إزالته من المفضلة",
    "message.messageSent": "تم إرسال الرسالة بنجاح!",
    "message.subscribed": "تم الاشتراك في النشرة الإخبارية بنجاح!",
    "message.error": "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
    "message.orderPlaced": "تم تأكيد الطلب بنجاح!",
    "message.productSaved": "تم حفظ المنتج بنجاح!",
    "message.productDeleted": "تم حذف المنتج بنجاح!",

    // Form Validation
    "validation.required": "هذا الحقل مطلوب",
    "validation.email": "يرجى إدخال عنوان بريد إلكتروني صحيح",
    "validation.minLength": "الحد الأدنى للطول هو {min} أحرف",
    "validation.maxLength": "الحد الأقصى للطول هو {max} أحرف",
    "validation.numeric": "يرجى إدخال رقم صحيح",
    "validation.positive": "يرجى إدخال رقم موجب",
  },
  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.products": "Produits",
    "nav.collections": "Collections",
    "nav.about": "À propos",
    "nav.contact": "Contact",
    "nav.cart": "Panier",
    "nav.wishlist": "Favoris",
    "nav.admin": "Admin",
    "nav.orders": "Commandes",
    "nav.faq": "FAQ",
    "nav.shipping": "Livraison",

    // Common
    "common.search": "Rechercher",
    "common.loading": "Chargement...",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.add": "Ajouter",
    "common.create": "Créer",
    "common.update": "Mettre à jour",
    "common.price": "Prix",
    "common.quantity": "Quantité",
    "common.total": "Total",
    "common.submit": "Soumettre",
    "common.close": "Fermer",
    "common.view": "Voir",
    "common.viewAll": "Voir tout",
    "common.learnMore": "En savoir plus",
    "common.shopNow": "Acheter maintenant",
    "common.viewDetails": "Voir les détails",
    "common.subscribe": "S'abonner",
    "common.send": "Envoyer",
    "common.name": "Nom",
    "common.email": "Email",
    "common.message": "Message",
    "common.subject": "Sujet",
    "common.category": "Catégorie",
    "common.status": "Statut",
    "common.date": "Date",
    "common.actions": "Actions",
    "common.description": "Description",
    "common.features": "Caractéristiques",
    "common.specifications": "Spécifications",
    "common.reviews": "Avis",
    "common.rating": "Note",

    // Products
    "product.addToCart": "Ajouter au panier",
    "product.addToWishlist": "Ajouter aux favoris",
    "product.removeFromWishlist": "Retirer des favoris",
    "product.outOfStock": "Rupture de stock",
    "product.inStock": "En stock",
    "product.featured": "En vedette",
    "product.sale": "Solde",
    "product.new": "Nouveau",
    "product.bestSeller": "Meilleure vente",
    "product.eco": "Écologique",
    "product.premium": "Premium",
    "product.originalPrice": "Prix original",
    "product.currentPrice": "Prix actuel",
    "product.selectVariant": "Sélectionner une variante",
    "product.color": "Couleur",
    "product.size": "Taille",
    "product.feature": "Caractéristique",

    // Cart & Checkout
    "cart.title": "Panier d'achat",
    "cart.empty": "Votre panier est vide",
    "cart.continueShopping": "Continuer les achats",
    "cart.proceedToCheckout": "Procéder au paiement",
    "cart.removeItem": "Supprimer l'article",
    "cart.updateQuantity": "Mettre à jour la quantité",
    "cart.subtotal": "Sous-total",
    "cart.shipping": "Livraison",
    "cart.tax": "Taxe",
    "cart.total": "Total",
    "checkout.title": "Commande",
    "checkout.billingAddress": "Adresse de facturation",
    "checkout.shippingAddress": "Adresse de livraison",
    "checkout.paymentMethod": "Mode de paiement",
    "checkout.placeOrder": "Passer la commande",

    // Wishlist
    "wishlist.title": "Ma liste de souhaits",
    "wishlist.empty": "Votre liste de souhaits est vide",
    "wishlist.addedToCart": "Ajouté au panier",
    "wishlist.removedFromWishlist": "Retiré de la liste de souhaits",

    // Search
    "search.title": "Résultats de recherche",
    "search.noResults": "Aucun produit trouvé",
    "search.resultsFor": "Résultats pour",
    "search.filters": "Filtres",
    "search.sortBy": "Trier par",
    "search.clearFilters": "Effacer tous les filtres",

    // Admin
    "admin.dashboard": "Tableau de bord",
    "admin.products": "Produits",
    "admin.orders": "Commandes",
    "admin.landingPages": "Pages de destination",
    "admin.templates": "Modèles",
    "admin.settings": "Paramètres",
    "admin.overview": "Aperçu",
    "admin.analytics": "Analyses",
    "admin.productPages": "Pages produits",
    "admin.customers": "Clients",
    "admin.addProduct": "Ajouter un produit",
    "admin.editProduct": "Modifier le produit",
    "admin.deleteProduct": "Supprimer le produit",
    "admin.productName": "Nom du produit",
    "admin.productDescription": "Description du produit",
    "admin.productPrice": "Prix du produit",
    "admin.productCategory": "Catégorie du produit",
    "admin.productStock": "Stock du produit",
    "admin.productImages": "Images du produit",
    "admin.productVariants": "Variantes du produit",
    "admin.addVariant": "Ajouter une variante",
    "admin.variantType": "Type de variante",
    "admin.variantValue": "Valeur de la variante",
    "admin.variantDescription": "Description de la variante",
    "admin.variantImages": "Images de la variante",
    "admin.variantStock": "Stock de la variante",

    // Admin Dashboard
    "admin.totalRevenue": "Chiffre d'affaires total",
    "admin.totalOrders": "Commandes",
    "admin.totalProducts": "Produits",
    "admin.activeCustomers": "Clients actifs",
    "admin.recentSales": "Ventes récentes",
    "admin.salesThisMonth": "Vous avez réalisé 265 ventes ce mois-ci.",

    // Admin Products
    "admin.productList": "Liste des produits",
    "admin.productListDesc": "Une liste de tous les produits dans votre magasin avec des variantes",
    "admin.searchProducts": "Rechercher des produits...",
    "admin.image": "Image",
    "admin.variants": "Variantes",
    "admin.moreVariants": "plus",
    "admin.basicInfo": "Informations de base",
    "admin.images": "Images",
    "admin.preview": "Aperçu",
    "admin.addImage": "Ajouter une image",
    "admin.imageUrl": "URL de l'image",
    "admin.altText": "Texte alternatif",
    "admin.primaryImage": "Image principale",
    "admin.noImagesAdded": "Aucune image ajoutée pour le moment",
    "admin.clickAddImage": 'Cliquez sur "Ajouter une image" pour commencer',
    "admin.variantName": "Nom de la variante",
    "admin.type": "Type",
    "admin.value": "Valeur",
    "admin.stockQuantity": "Quantité en stock",
    "admin.noVariantsAdded": "Aucune variante ajoutée pour le moment",
    "admin.clickAddVariant":
      'Cliquez sur "Ajouter une variante" pour créer des options de couleur, de taille ou de fonctionnalité',
    "admin.productPreview": "Aperçu du produit",
    "admin.availableOptions": "Options disponibles:",
    "admin.units": "unités",

    // Admin Orders
    "admin.manageOrders": "Gérer les commandes des clients et suivre l'exécution",
    "admin.searchOrders": "Rechercher des commandes...",
    "admin.filterByStatus": "Filtrer par statut",
    "admin.newOrder": "Nouvelle Commande",
    "admin.allStatus": "Tous les statuts",
    "admin.pending": "En attente",
    "admin.processing": "En cours de traitement",
    "admin.shipped": "Expédié",
    "admin.delivered": "Livré",
    "admin.cancelled": "Annulé",
    "admin.orderList": "Liste des commandes",
    "admin.recentOrders": "Commandes récentes de vos clients",
    "admin.orderId": "ID de commande",
    "admin.customer": "Client",
    "admin.orderDetails": "Détails de la commande",
    "admin.completeOrderInfo": "Informations complètes sur la commande et détails du client",
    "admin.customerInfo": "Informations sur le client",
    "admin.orderDate": "Date de la commande",
    "admin.shippingAddress": "Adresse de livraison",

    // Admin Templates
    "admin.landingPageTemplates": "Modèles de pages de destination",
    "admin.createManageTemplates": "Créer et gérer des modèles réutilisables pour les pages de destination",
    "admin.quickTemplate": "Modèle rapide",
    "admin.buildTemplate": "Construire un modèle",
    "admin.createQuickTemplate": "Créer un modèle rapide",
    "admin.basicTemplateCustomize": "Créer un modèle de base que vous pourrez personnaliser ultérieurement",
    "admin.templateName": "Nom du modèle",
    "admin.createTemplate": "Créer un modèle",
    "admin.default": "Par défaut",
    "admin.sections": "sections",
    "admin.created": "Créé",

    // Admin Settings
    "admin.storeConfiguration": "Gérer la configuration et les préférences de votre magasin",
    "admin.store": "Magasin",
    
    "admin.seo": "SEO",
    "admin.email": "Email",
    "admin.payment": "Paiement",
    "admin.theme": "Thème",
    "admin.security": "Sécurité",
    "admin.storeInformation": "Informations sur le magasin",
    "admin.basicStoreInfo": "Informations de base sur votre magasin",
    "admin.storeName": "Nom du magasin",
    "admin.storeEmail": "Email du magasin",
    "admin.storeDescription": "Description du magasin",
    "admin.phoneNumber": "Numéro de téléphone",
    "admin.address": "Adresse",
    "admin.saveStoreSettings": "Enregistrer les paramètres du magasin",
    "admin.seoConfiguration": "Configuration SEO",
    "admin.optimizeStore": "Optimiser votre magasin pour les moteurs de recherche",
    "admin.siteTitle": "Titre du site",
    "admin.metaDescription": "Meta Description",
    "admin.keywords": "Mots-clés",
    "admin.analyticsTracking": "Analyses et suivi",
    "admin.googleAnalyticsId": "ID Google Analytics",
    "admin.facebookPixelId": "ID Pixel Facebook",
    "admin.enableTracking": "Activer le suivi et l'analyse",
    "admin.saveSeoSettings": "Enregistrer les paramètres SEO",
    "admin.emailConfiguration": "Configuration de l'email",
    "admin.configureEmailNotifications": "Configurer les notifications par email et les paramètres SMTP",
    "admin.notificationSettings": "Paramètres de notification",
    "admin.enableEmailNotifications": "Activer les notifications par email",
    "admin.sendOrderConfirmations": "Envoyer des confirmations de commande",
    "admin.sendMarketingEmails": "Envoyer des emails marketing",
    "admin.smtpConfiguration": "Configuration SMTP",
    "admin.smtpHost": "Hôte SMTP",
    "admin.smtpPort": "Port SMTP",
    "admin.smtpUsername": "Nom d'utilisateur SMTP",
    "admin.smtpPassword": "Mot de passe SMTP",
    "admin.saveEmailSettings": "Enregistrer les paramètres d'email",
    "admin.paymentShipping": "Paiement et livraison",
    "admin.configurePaymentShipping": "Configurer le traitement des paiements et les options de livraison",
    "admin.currency": "Devise",
    "admin.taxRate": "Taux de taxe (%)",
    "admin.standardShippingRate": "Frais de livraison standard",
    "admin.freeShippingThreshold": "Seuil de livraison gratuite",
    "admin.paymentMethods": "Méthodes de paiement",
    "admin.active": "Actif",
    "admin.inactive": "Inactif",
    "admin.creditCards": "Cartes de crédit",
    "admin.paypal": "PayPal",
    "admin.applePay": "Apple Pay",
    "admin.googlePay": "Google Pay",
    "admin.savePaymentSettings": "Enregistrer les paramètres de paiement",
    "admin.themeCustomization": "Personnalisation du thème",
    "admin.customizeStoreLook": "Personnaliser l'apparence de votre magasin",
    "admin.primaryColor": "Couleur primaire",
    "admin.secondaryColor": "Couleur secondaire",
    "admin.accentColor": "Couleur d'accentuation",
    "admin.enableDarkMode": "Activer le mode sombre",
    "admin.logoBranding": "Logo et image de marque",
    "admin.storeLogo": "Logo du magasin",
    "admin.uploadStoreLogo": "Télécharger le logo de votre magasin",
    "admin.chooseFile": "Choisir un fichier",
    "admin.favicon": "Favicon",
    "admin.uploadFavicon": "Télécharger le favicon (32x32px)",
    "admin.saveThemeSettings": "Enregistrer les paramètres du thème",
    "admin.securitySettings": "Paramètres de sécurité",
    "admin.configureSecurityAuth": "Configurer les options de sécurité et d'authentification",
    "admin.enableTwoFactor": "Activer l'authentification à deux facteurs",
    "admin.enforceStrongPasswords": "Appliquer des exigences de mot de passe fort",
    "admin.sessionTimeout": "Délai d'expiration de la session (minutes)",
    "admin.securityStatus": "État de la sécurité",
    "admin.sslCertificate": "Certificat SSL",
    "admin.httpsEncryption": "Cryptage HTTPS",
    "admin.firewallProtection": "Protection pare-feu",
    "admin.ddosProtection": "Protection DDoS",
    "admin.saveSecuritySettings": "Enregistrer les paramètres de sécurité",

    // Admin Navigation
    "admin.viewStore": "Voir le magasin",
    "admin.adminPanel": "Panneau d'administration",
    "admin.ecommerceAdmin": "Admin E-commerce",
    "admin.storePerformance": "Voici un aperçu des performances de votre magasin.",
    "admin.fromLastMonth": "du mois dernier",
    "admin.sinceLastHour": "depuis la dernière heure",

    // Home Page
    "home.hero.title": "Découvrez des produits incroyables",
    "home.hero.subtitle":
      "Achetez les dernières tendances et trouvez tout ce dont vous avez besoin en un seul endroit. Produits de qualité, prix avantageux, livraison rapide.",
    "home.features.freeShipping": "Livraison gratuite",
    "home.features.freeShippingDesc": "Livraison gratuite pour les commandes de plus de 50 $",
    "home.features.securePayment": "Paiement sécurisé",
    "home.features.securePaymentDesc": "Vos informations de paiement sont sécurisées",
    "home.features.support": "Support 24/7",
    "home.features.supportDesc": "Obtenez de l'aide quand vous en avez besoin",
    "home.featuredProducts.title": "Produits en vedette",
    "home.featuredProducts.subtitle":
      "Découvrez nos articles les plus populaires, soigneusement sélectionnés pour la qualité et la valeur",
    "home.collections.title": "Acheter par collection",
    "home.collections.subtitle": "Explorez nos collections organisées conçues pour chaque style de vie",
    "home.newsletter.title": "Restez informé",
    "home.newsletter.subtitle":
      "Abonnez-vous à notre newsletter et soyez le premier à connaître les nouveaux produits et les offres exclusives",
    "home.newsletter.placeholder": "Entrez votre email",

    // About Page
    "about.title": "À propos de nous",
    "about.subtitle": "En savoir plus sur notre entreprise et notre mission",
    "about.story.title": "Notre histoire",
    "about.mission.title": "Notre mission",
    "about.values.title": "Nos valeurs",
    "about.team.title": "Rencontrez notre équipe",

    // Contact Page
    "contact.title": "Contactez-nous",
    "contact.subtitle":
      "Vous avez une question, besoin d'aide ou souhaitez partager des commentaires ? Nous sommes là pour vous aider et aimerions avoir de vos nouvelles.",
    "contact.info.title": "Informations de contact",
    "contact.info.email": "Envoyez-nous un email",
    "contact.info.phone": "Appelez-nous",
    "contact.info.address": "Visitez-nous",
    "contact.info.hours": "Heures d'ouverture",
    "contact.form.title": "Envoyez-nous un message",
    "contact.form.subtitle": "Remplissez le formulaire ci-dessous et nous vous répondrons dès que possible.",
    "contact.form.fullName": "Nom complet",
    "contact.form.emailAddress": "Adresse email",
    "contact.form.messageText": "Message",
    "contact.form.sendMessage": "Envoyer le message",
    "contact.quickHelp.title": "Aide rapide",
    "contact.quickHelp.trackOrder": "Suivre votre commande",
    "contact.quickHelp.trackOrderDesc": "Vérifier le statut de la commande et la livraison",
    "contact.quickHelp.faq": "FAQ",
    "contact.quickHelp.faqDesc": "Trouvez des réponses aux questions courantes",
    "contact.quickHelp.liveChat": "Chat en direct",
    "contact.quickHelp.liveChatDesc": "Chattez avec notre équipe de support",

    // FAQ Page
    "faq.title": "Questions fréquemment posées",
    "faq.subtitle": "Trouvez des réponses aux questions courantes sur nos produits et services",
    "faq.searchPlaceholder": "Rechercher dans la FAQ...",

    // Footer
    "footer.company": "E-Store",
    "footer.companyDesc":
      "Votre destination de confiance pour les achats en ligne de produits de qualité à des prix avantageux.",
    "footer.quickLinks": "Liens rapides",
    "footer.customerService": "Service client",
    "footer.connect": "Se connecter",
    "footer.connectDesc": "Suivez-nous sur les réseaux sociaux pour les mises à jour et les offres exclusives.",
    "footer.copyright": "© 2024 E-Store. Tous droits réservés.",

    // Collections
    "collections.electronics": "Électronique",
    "collections.electronicsDesc": "Derniers gadgets technologiques et accessoires",
    "collections.lifestyle": "Style de vie",
    "collections.lifestyleDesc": "Produits pour la vie moderne",
    "collections.fitness": "Fitness",
    "collections.fitnessDesc": "Essentiels de santé et bien-être",
    "collections.products": "produits",

    // Messages & Notifications
    "message.addedToCart": "Ajouté au panier avec succès !",
    "message.addedToWishlist": "Ajouté aux favoris !",
    "message.removedFromWishlist": "Retiré des favoris",
    "message.messageSent": "Message envoyé avec succès !",
    "message.subscribed": "Abonnement à la newsletter réussi !",
    "message.error": "Quelque chose s'est mal passé. Veuillez réessayer.",
    "message.orderPlaced": "Commande passée avec succès !",
    "message.productSaved": "Produit enregistré avec succès !",
    "message.productDeleted": "Produit supprimé avec succès !",

    // Form Validation
    "validation.required": "Ce champ est requis",
    "validation.email": "Veuillez entrer une adresse email valide",
    "validation.minLength": "La longueur minimale est de {min} caractères",
    "validation.maxLength": "La longueur maximale est de {max} caractères",
    "validation.numeric": "Veuillez entrer un nombre valide",
    "validation.positive": "Veuillez entrer un nombre positif",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && ["en", "ar", "fr"].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr"
    document.documentElement.lang = lang
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
